server:
  port: 8900

spring:
  shardingsphere:
    datasource:
      names: m1
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.74.128:3306/edu_db_1?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: dahuacloud
      m2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.74.128:3306/edu_db_2?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: dahuacloud
    sharding:
      tables:
        course:
          actual-data-nodes: m$->{1..2}.course_$->{1..2}
          key-generate-strategy:
            column: id
            key-generator-name: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: course_$->{id % 2 + 1}
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: m$->{user_id % 2 + 1}
    props:
      sql: true
  application:
    name: shareding-seata-tm
    cloud:
      alibaba:
        seata:
          tx-service-group: my_test_tx_group
    #配置数据源
    main:
      allow-bean-definition-overriding: true



seata:
  enabled: true
  service:
    vgroup-mapping:
      my_test_tx_group: default
    enable-degrade: false
    disable-global-transaction: false


eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      version: v7
  client:
    serviceUrl:
      defaultZone: http://user:123456@${EUREKA:eureka7001.com}:7001/eureka/ #注册中心地址:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

