spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  application:
    name: sharding-seata-rm
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.74.130:3306/user_db?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: dahuacloud

  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      version: v7
  client:
    serviceUrl:
      defaultZone: http://user:123456@${EUREKA:eureka7001.com}:7001/eureka/ #注册中心地址:

seata:
  enabled: true
  service:
    vgroup-mapping:
      my_test_tx_group: default
    enable-degrade: false
    disable-global-transaction: false